CREATE SCHEMA `SIS`;

-- MySQL Script generated by MySQL Workbench
-- Tue Oct 11 12:46:51 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sis
-- -----------------------------------------------------
USE `sis` ;


-- -----------------------------------------------------
-- Table `sis`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `deleted_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `hva_id` VARCHAR(255) NULL,
  `student_nr` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `hva_id_UNIQUE` (`hva_id` ASC),
  UNIQUE INDEX `student_nr_UNIQUE` (`student_nr` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis`.`roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis`.`privileges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis`.`privileges` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `system_name` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis`.`study_programs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis`.`study_programs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `group_prefix` VARCHAR(45) NOT NULL,
  `duration_years` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `group_prefix_UNIQUE` (`group_prefix` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis`.`courses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `study_program_id` INT UNSIGNED NOT NULL,
  `semester` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `ECTS` INT NOT NULL,
  `type` ENUM('regular', 'project') NOT NULL,
  PRIMARY KEY (`id`, `study_program_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_courses_study_programs1_idx` (`study_program_id` ASC),
  CONSTRAINT `fk_courses_study_programs1`
    FOREIGN KEY (`study_program_id`)
    REFERENCES `sis`.`study_programs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis`.`grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis`.`grades` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `course_id` INT UNSIGNED NOT NULL,
  `type` VARCHAR(45) NULL,
  `grade` VARCHAR(45) NULL,
  `passed` TINYINT(1) NULL,
  PRIMARY KEY (`id`, `course_id`),
  INDEX `fk_grades_courses1_idx` (`course_id` ASC),
  CONSTRAINT `fk_grades_courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `sis`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis`.`groups` (
  `id` INT UNSIGNED NOT NULL,
  `graduation_year` YEAR NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis`.`group_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis`.`group_user` (
  `group_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  INDEX `fk_group_user_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_group_user_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sis`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_user_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `sis`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis`.`privilege_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis`.`privilege_role` (
  `privilege_id` INT UNSIGNED NOT NULL,
  `role_id` INT UNSIGNED NULL,
  INDEX `fk_privilege_role_privileges1_idx` (`privilege_id` ASC),
  INDEX `fk_privilege_role_roles1_idx` (`role_id` ASC),
  CONSTRAINT `fk_privilege_role_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `sis`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_privilege_role_privileges1`
    FOREIGN KEY (`privilege_id`)
    REFERENCES `sis`.`privileges` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis`.`role_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis`.`role_user` (
  `role_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  INDEX `fk_role_user_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_role_user_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `sis`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_user_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `sis`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis`.`course_teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis`.`course_teacher` (
  `course_id` INT UNSIGNED NOT NULL,
  `teacher_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`course_id`),
  INDEX `fk_course_teacher_courses1_idx` (`teacher_id` ASC),
  CONSTRAINT `fk_course_teacher_courses1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `sis`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_teacher_users1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `sis`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis`.`exams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis`.`exams` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `course_id` INT UNSIGNED NOT NULL,
  `location` TEXT NULL,
  `date_and_time` DATETIME NULL,
  `type` ENUM('regular', 're-exam') NOT NULL,
  PRIMARY KEY (`id`, `course_id`),
  INDEX `fk_exams_courses1_idx` (`course_id` ASC),
  CONSTRAINT `fk_exams_courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `sis`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
